In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('/content/india_job_market_dataset.csv')
df

,Job ID,Job Title,Company Name,Job Location,Job Type,Salary Range,Experience Required,Posted Date,Application Deadline,Job Portal,Number of Applicants,Education Requirement,Skills Required,Remote/Onsite,Company,Size
0,JOB1,Software Engineer,Amazon,Ahmedabad,Full-time,5-8 LPA,2-5 years,16-01-2025,25-01-2025,LinkedIn,23,PhD,"C++, SQL, Python",Remote,Small,(1-50)
1,JOB2,Marketing Executive,Infosys,Ahmedabad,Internship,5-8 LPA,2-5 years,25-12-2024,19-01-2025,Indeed,462,MBA,"SQL, C++, Python",Remote,Large,(500+)
2,JOB3,Financial Analyst,Deloitte,Jaipur,Contract,20+ LPA,5-10 years,22-01-2025,29-01-2025,Naukri.com,430,M.Tech,"Machine Learning, Excel, React",Remote,Large,(500+)
3,JOB4,Business Analyst,Amazon,Delhi,Full-time,20+ LPA,2-5 years,07-01-2025,06-02-2025,LinkedIn,387,B.Tech,"Machine Learning, Python, SQL",Hybrid,Small,(1-50)
4,JOB5,Software Engineer,Infosys,Delhi,Full-time,12-20 LPA,10+ years,26-12-2024,08-01-2025,Indeed,199,MBA,"UI/UX, C++, Java",Onsite,Small,(1-50)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,JOB19996,Marketing Executive,Deloitte,Pune,Full-time,5-8 LPA,2-5 years,13-01-2025,05-02-2025,Indeed,171,PhD,"Machine Learning, Python, AWS",Remote,Small,(1-50)
19996,JOB19997,Business Analyst,Accenture,Bangalore,Internship,20+ LPA,0-2 years,08-01-2025,27-01-2025,LinkedIn,482,MBA,"Digital Marketing, React, Machine Learning",Onsite,Medium,(51-500)
19997,JOB19998,Graphic Designer,Wipro,Jaipur,Part-time,5-8 LPA,5-10 years,26-12-2024,16-01-2025,Naukri.com,319,PhD,"Machine Learning, Excel, Digital Marketing",Onsite,Small,(1-50)
19998,JOB19999,Sales Representative,Infosys,Kolkata,Internship,12-20 LPA,2-5 years,20-01-2025,09-02-2025,Naukri.com,178,M.Tech,"Excel, C++, React",Onsite,Large,(500+)
19999,JOB20000,Business Analyst,Accenture,Mumbai,Part-time,5-8 LPA,0-2 years,30-12-2024,13-01-2025,Indeed,88,B.Sc,"Java, C++, Python",Remote,Medium,(51-500)

In [3]:
df.head()

,Job ID,Job Title,Company Name,Job Location,Job Type,Salary Range,Experience Required,Posted Date,Application Deadline,Job Portal,Number of Applicants,Education Requirement,Skills Required,Remote/Onsite,Company,Size
0,JOB1,Software Engineer,Amazon,Ahmedabad,Full-time,5-8 LPA,2-5 years,16-01-2025,25-01-2025,LinkedIn,23,PhD,"C++, SQL, Python",Remote,Small,(1-50)
1,JOB2,Marketing Executive,Infosys,Ahmedabad,Internship,5-8 LPA,2-5 years,25-12-2024,19-01-2025,Indeed,462,MBA,"SQL, C++, Python",Remote,Large,(500+)
2,JOB3,Financial Analyst,Deloitte,Jaipur,Contract,20+ LPA,5-10 years,22-01-2025,29-01-2025,Naukri.com,430,M.Tech,"Machine Learning, Excel, React",Remote,Large,(500+)
3,JOB4,Business Analyst,Amazon,Delhi,Full-time,20+ LPA,2-5 years,07-01-2025,06-02-2025,LinkedIn,387,B.Tech,"Machine Learning, Python, SQL",Hybrid,Small,(1-50)
4,JOB5,Software Engineer,Infosys,Delhi,Full-time,12-20 LPA,10+ years,26-12-2024,08-01-2025,Indeed,199,MBA,"UI/UX, C++, Java",Onsite,Small,(1-50)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Job ID                 20000 non-null  object
 1   Job Title              20000 non-null  object
 2   Company Name           20000 non-null  object
 3   Job Location           20000 non-null  object
 4   Job Type               20000 non-null  object
 5   Salary Range           20000 non-null  object
 6   Experience Required    20000 non-null  object
 7   Posted Date            20000 non-null  object
 8   Application Deadline   20000 non-null  object
 9   Job Portal             20000 non-null  object
 10  Number of Applicants   20000 non-null  int64
 11  Education Requirement  20000 non-null  object
 12  Skills Required        20000 non-null  object
 13  Remote/Onsite          20000 non-null  object
 14  Company                20000 non-null  object
 15  Size                   20000 non-null  object
dtypes: int64(1), object(15)
memory usage: 2.4+ MB

In [5]:
df.columns

Index(['Job ID', 'Job Title', 'Company Name', 'Job Location', 'Job Type',
       'Salary Range', 'Experience Required', 'Posted Date',
       'Application Deadline', 'Job Portal', 'Number of Applicants',
       'Education Requirement', 'Skills Required', 'Remote/Onsite', 'Company',
       'Size'],
      dtype='object')

In [6]:
df.isnull().sum()

Job ID                   0
Job Title                0
Company Name             0
Job Location             0
Job Type                 0
Salary Range             0
Experience Required      0
Posted Date              0
Application Deadline     0
Job Portal               0
Number of Applicants     0
Education Requirement    0
Skills Required          0
Remote/Onsite            0
Company                  0
Size                     0
dtype: int64

In [7]:
df.columns=df.columns.str.lower()

In [8]:
df.columns

Index(['job id', 'job title', 'company name', 'job location', 'job type',
       'salary range', 'experience required', 'posted date',
       'application deadline', 'job portal', 'number of applicants',
       'education requirement', 'skills required', 'remote/onsite', 'company',
       'size'],
      dtype='object')

In [10]:
df.columns=df.columns.str.replace(" ","_")
df.columns=df.columns.str.replace("/","_")

In [11]:
df.columns

Index(['job_id', 'job_title', 'company_name', 'job_location', 'job_type',
       'salary_range', 'experience_required', 'posted_date',
       'application_deadline', 'job_portal', 'number_of_applicants',
       'education_requirement', 'skills_required', 'remote_onsite', 'company',
       'size'],
      dtype='object')

In [18]:
df['experience_required']=df['experience_required'].str.replace("years","",regex=False)
df['experience_required']=df['experience_required'].astype(str)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   job_id                 20000 non-null  object
 1   job_title              20000 non-null  object
 2   company_name           20000 non-null  object
 3   job_location           20000 non-null  object
 4   job_type               20000 non-null  object
 5   salary_range           20000 non-null  object
 6   experience_required    20000 non-null  object
 7   posted_date            20000 non-null  object
 8   application_deadline   20000 non-null  object
 9   job_portal             20000 non-null  object
 10  number_of_applicants   20000 non-null  int64
 11  education_requirement  20000 non-null  object
 12  skills_required        20000 non-null  object
 13  remote_onsite          20000 non-null  object
 14  company                20000 non-null  object
 15  size                   20000 non-null  object
dtypes: int64(1), object(15)
memory usage: 2.4+ MB

In [20]:
#Creating a column Grouping
def Agg(education_requirement):
  if "0-2" in education_requirement:
    return "L1"
  elif "2-5" in education_requirement:
    return "L2"
  elif "5-10" in education_requirement:
    return "L3"
  elif "10+" in education_requirement:
    return "L4"
  else:
    return "Unknown"

df['experience_level']=df['experience_required'].apply(Agg)

In [21]:
df[['experience_level','experience_required']]

      experience_level experience_required
0                   L2                2-5
1                   L2                2-5
2                   L3               5-10
3                   L2                2-5
4                   L4                10+
...                ...                 ...
19995               L2                2-5
19996               L1                0-2
19997               L3               5-10
19998               L2                2-5
19999               L1                0-2

[20000 rows x 2 columns]

In [ ]:
#df['company_level']=df["company_size"].str.extract(r"\((.*?)\)")

In [23]:
df['company_level']=df["company_size"].str.extract(r"^([A-Za-z]+)")

In [25]:
df[['company','size']]

      company      size
0       Small    (1-50)
1       Large    (500+)
2       Large    (500+)
3       Small    (1-50)
4       Small    (1-50)
...       ...       ...
19995   Small    (1-50)
19996  Medium  (51-500)
19997   Small    (1-50)
19998   Large    (500+)
19999  Medium  (51-500)

[20000 rows x 2 columns]

In [26]:
df.head(5)

,job_id,job_title,company_name,job_location,job_type,salary_range,experience_required,posted_date,application_deadline,job_portal,number_of_applicants,education_requirement,skills_required,remote_onsite,company,size,experience_level
0,JOB1,Software Engineer,Amazon,Ahmedabad,Full-time,5-8 LPA,2-5,16-01-2025,25-01-2025,LinkedIn,23,PhD,"C++, SQL, Python",Remote,Small,(1-50),L2
1,JOB2,Marketing Executive,Infosys,Ahmedabad,Internship,5-8 LPA,2-5,25-12-2024,19-01-2025,Indeed,462,MBA,"SQL, C++, Python",Remote,Large,(500+),L2
2,JOB3,Financial Analyst,Deloitte,Jaipur,Contract,20+ LPA,5-10,22-01-2025,29-01-2025,Naukri.com,430,M.Tech,"Machine Learning, Excel, React",Remote,Large,(500+),L3
3,JOB4,Business Analyst,Amazon,Delhi,Full-time,20+ LPA,2-5,07-01-2025,06-02-2025,LinkedIn,387,B.Tech,"Machine Learning, Python, SQL",Hybrid,Small,(1-50),L2
4,JOB5,Software Engineer,Infosys,Delhi,Full-time,12-20 LPA,10+,26-12-2024,08-01-2025,Indeed,199,MBA,"UI/UX, C++, Java",Onsite,Small,(1-50),L4

In [27]:
df.drop_duplicates()

,job_id,job_title,company_name,job_location,job_type,salary_range,experience_required,posted_date,application_deadline,job_portal,number_of_applicants,education_requirement,skills_required,remote_onsite,company,size,experience_level
0,JOB1,Software Engineer,Amazon,Ahmedabad,Full-time,5-8 LPA,2-5,16-01-2025,25-01-2025,LinkedIn,23,PhD,"C++, SQL, Python",Remote,Small,(1-50),L2
1,JOB2,Marketing Executive,Infosys,Ahmedabad,Internship,5-8 LPA,2-5,25-12-2024,19-01-2025,Indeed,462,MBA,"SQL, C++, Python",Remote,Large,(500+),L2
2,JOB3,Financial Analyst,Deloitte,Jaipur,Contract,20+ LPA,5-10,22-01-2025,29-01-2025,Naukri.com,430,M.Tech,"Machine Learning, Excel, React",Remote,Large,(500+),L3
3,JOB4,Business Analyst,Amazon,Delhi,Full-time,20+ LPA,2-5,07-01-2025,06-02-2025,LinkedIn,387,B.Tech,"Machine Learning, Python, SQL",Hybrid,Small,(1-50),L2
4,JOB5,Software Engineer,Infosys,Delhi,Full-time,12-20 LPA,10+,26-12-2024,08-01-2025,Indeed,199,MBA,"UI/UX, C++, Java",Onsite,Small,(1-50),L4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,JOB19996,Marketing Executive,Deloitte,Pune,Full-time,5-8 LPA,2-5,13-01-2025,05-02-2025,Indeed,171,PhD,"Machine Learning, Python, AWS",Remote,Small,(1-50),L2
19996,JOB19997,Business Analyst,Accenture,Bangalore,Internship,20+ LPA,0-2,08-01-2025,27-01-2025,LinkedIn,482,MBA,"Digital Marketing, React, Machine Learning",Onsite,Medium,(51-500),L1
19997,JOB19998,Graphic Designer,Wipro,Jaipur,Part-time,5-8 LPA,5-10,26-12-2024,16-01-2025,Naukri.com,319,PhD,"Machine Learning, Excel, Digital Marketing",Onsite,Small,(1-50),L3
19998,JOB19999,Sales Representative,Infosys,Kolkata,Internship,12-20 LPA,2-5,20-01-2025,09-02-2025,Naukri.com,178,M.Tech,"Excel, C++, React",Onsite,Large,(500+),L2
19999,JOB20000,Business Analyst,Accenture,Mumbai,Part-time,5-8 LPA,0-2,30-12-2024,13-01-2025,Indeed,88,B.Sc,"Java, C++, Python",Remote,Medium,(51-500),L1

In [68]:
df.shape

(20000, 18)

In [35]:
df['posted_date']=pd.to_datetime(df['posted_date'],format="%d-%m-%y")

In [60]:
df['application_deadline']=pd.to_datetime(df['application_deadline'],format="%d-%m-%y")

df['days_of_deadline']=(df['application_deadline']-df['posted_date']).dt.days

In [41]:
df['year']=df['posted_date'].dt.year
df['month']=df['posted_date'].dt.month
df['day']=df['posted_date'].dt.day

In [67]:
df=df.drop('year',axis=1)

In [63]:
df=df.drop('month',axis=1)

In [65]:
df=df.drop('day',axis=1)

In [69]:
df

,job_id,job_title,company_name,job_location,job_type,salary_range,experience_required,posted_date,application_deadline,job_portal,number_of_applicants,education_requirement,skills_required,remote_onsite,company,size,experience_level,days_of_deadline
0,JOB1,Software Engineer,Amazon,Ahmedabad,Full-time,5-8 LPA,2-5,2025-01-16,2025-01-25,LinkedIn,23,PhD,"C++, SQL, Python",Remote,Small,(1-50),L2,9
1,JOB2,Marketing Executive,Infosys,Ahmedabad,Internship,5-8 LPA,2-5,2024-12-25,2025-01-19,Indeed,462,MBA,"SQL, C++, Python",Remote,Large,(500+),L2,25
2,JOB3,Financial Analyst,Deloitte,Jaipur,Contract,20+ LPA,5-10,2025-01-22,2025-01-29,Naukri.com,430,M.Tech,"Machine Learning, Excel, React",Remote,Large,(500+),L3,7
3,JOB4,Business Analyst,Amazon,Delhi,Full-time,20+ LPA,2-5,2025-01-07,2025-02-06,LinkedIn,387,B.Tech,"Machine Learning, Python, SQL",Hybrid,Small,(1-50),L2,30
4,JOB5,Software Engineer,Infosys,Delhi,Full-time,12-20 LPA,10+,2024-12-26,2025-01-08,Indeed,199,MBA,"UI/UX, C++, Java",Onsite,Small,(1-50),L4,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,JOB19996,Marketing Executive,Deloitte,Pune,Full-time,5-8 LPA,2-5,2025-01-13,2025-02-05,Indeed,171,PhD,"Machine Learning, Python, AWS",Remote,Small,(1-50),L2,23
19996,JOB19997,Business Analyst,Accenture,Bangalore,Internship,20+ LPA,0-2,2025-01-08,2025-01-27,LinkedIn,482,MBA,"Digital Marketing, React, Machine Learning",Onsite,Medium,(51-500),L1,19
19997,JOB19998,Graphic Designer,Wipro,Jaipur,Part-time,5-8 LPA,5-10,2024-12-26,2025-01-16,Naukri.com,319,PhD,"Machine Learning, Excel, Digital Marketing",Onsite,Small,(1-50),L3,21
19998,JOB19999,Sales Representative,Infosys,Kolkata,Internship,12-20 LPA,2-5,2025-01-20,2025-02-09,Naukri.com,178,M.Tech,"Excel, C++, React",Onsite,Large,(500+),L2,20
19999,JOB20000,Business Analyst,Accenture,Mumbai,Part-time,5-8 LPA,0-2,2024-12-30,2025-01-13,Indeed,88,B.Sc,"Java, C++, Python",Remote,Medium,(51-500),L1,14

In [70]:
df.to_csv("indian_job_market.csv",index=False)